### ISSUE TITLE
Data-driven submission form v1

### ISSUE THREAD

**Issue by lacabra** [unicef/publicgoods-roadmap#3]
The current [submission form](https://digitalpublicgoods.net/submission) is implemented using Google Forms, and we have observed several missing features that we would like to add:
- ability to save current session and be able to resume at a later time
- more granularity and control in the fields that get displayed, introducing conditional logic at the question level instead of at the section level

An initial prototype is built at [this repository](https://github.com/lacabra/submission-digitalpublicgoods/), using the following technology stack:
* This webapp is built using [Next.js](https://nextjs.org/) as a React Framework and deployed using [Vercel](https://vercel.com/). 
* The forms are [Data Driven Forms](https://data-driven-forms.org/), configured through this JSON schema: [schema.json](schemas/schema.json).

## Design Requirements

- [X] Support for standard HTML Field Types: Drop downs, Multiple choice, Short answer/long answer 
- [X] Descriptive paragraphs (helperText)
- [X] Field validation
- [X] Required fields
- [X] Questions being hidden and presenting themselves based on previous questions i.e. If you select SDG 4
- [ ] Progress indicator
- [ ] Sections
- [ ] Logic (skip questions/go to question based on response) 
- [ ] Login (authenticate / user management) 
- [ ] Autosaving 
- [ ] Save and come back to continue editing
- [ ] Collect emails 
- [ ] Mailchimp integration: automatic sending of emails based on certain form responses

* Admin Interface:
    - [ ] Admin Interface
    - [ ] Review forms individually
    - [ ] Some data aggregated (summary view) 
    - [ ] Percentage of docs through forms
    - [ ] How many forms were not complete (aborted applications) 

* For Communities of Practice: 
    - [ ] P1. Keyword search through applications (i.e. to find ones related to health, finance, climate)
    - [ ] The ability to export project applications (same as the ability to review forms individually but also to have in a form you can send people) 
    - [ ] P2 - A review tool for CoP members who can vote yes/no on projects?
