### ISSUE TITLE
Submission Form Improvements

### ISSUE THREAD

**Issue by lacabra** [unicef/publicgoods-roadmap#30]
The current submission form was made live in early May at https://digitalpublicgoods.net/submission. The form is built at [this repository](https://github.com/lacabra/submission-digitalpublicgoods/), using the following technology stack:

This webapp is built using [Next.js](https://nextjs.org/) as a React Framework and deployed using [Vercel](https://vercel.com/). 

The forms are [Data Driven Forms](https://data-driven-forms.org/), configured through this JSON schema: [schema.js](schemas/schema.js).

This Epic follows the work started in #3. 

During the months of April/May 2021, a design exercise was conducted focused on the pre-nomination experience, documented [here](https://miro.com/app/board/o9J_lLLr-aA=/). From that work, some features are documented below (requires additional work extracting additional features).

The following additional features are desired:

- [ ] Section headers
- [ ] Progress indicator
- [ ] Login (authenticate / user management) 
- [ ] Save and come back to continue editing
- [ ] Ability to edit an existing entry in the registry
- [ ] Detect duplicates
