### ISSUE TITLE
Map Visualization

### ISSUE THREAD

**Issue by lacabra** [unicef/publicgoods-roadmap#34]
UNICEF is a co-champion of the Digital Public Goods Alliance (DPGA), a multi-stakeholder initiative to facilitate the discovery, development, use, and investment in digital public goods. Endorsed by the UN Secretary General’s Roadmap for Digital Cooperation, the DPGA defines digital public goods as: “open source software, open data, open AI models, open standards and open content that adhere to privacy and other applicable laws and best practices, do no harm, and help attain the SDGs.”

For the last two years, we have been building a registry of digital public goods compiling nominations for digital public goods (a.k.a. nominees), and screening those goods against the Digital Public Goods Standard, after which they become digital public goods. We have been compiling all this information in an open repository, and there is a wealth of data that we want to make more readily available, and explore additional ways to get insights from that growing dataset.

One aspect of this dataset that remains untapped is its geographical dimension. We have already compiled the lists of countries where digital public goods have been developed and implemented, but we have yet to visualize all this data.

The goal of this project is to build a map visualization of multiple dimensions of data related to the geographic extent of digital public goods. The multiple dimensions come from aspects like:

* countries in which a good was developed
* countries where the good has been implemented
* countries participating in the Pathfinder activities of the Digital Public Goods Alliance (think of early adopters)
* countries with implementations of goods part of the DPGA communities of practice: Digital Health, Climate Adaptation, Financial Inclusion

**Proposed Implementation Plan**

1. The map should be developed using [Mapbox](https://www.mapbox.com/), and preferably as a React app (using the [react-mapbox-gl](www.npmjs.com/package/react-mapbox-gl) library).
2. Country data from existing digital public goods will be pulled from this existing (and growing) [set of JSON files](https://github.com/unicef/publicgoods-candidates/tree/master/digitalpublicgoods), which has a very clear [data schema](github.com/unicef/publicgoods-candidates/blob/master/screening-schema.json) defined.
3. The map should also be able to pull data from a Google Spreadsheet to allow for non-developer program staff to update data about their current programmatic activities within the DPGA
4. A similar implementation that can be used as a reference for a subset of the features required for this project can be found on [this repository](github.com/lacabra/ooi-project-visualization), alongside the [live website](https://ooi-map.vercel.app/).
5. At the end of the project the map should be accessible at a location like https://digitalpublicgoods.net/map (this link does not exist yet!). This is a static HTML website (a daily snapshot of a Wordpress site that gets subsequently processed to add React components), so some tweaks will have to be made to mold it into the existing infrastructure. Again, there is similar already existing functionality that can be leveraged in [this other repository](https://github.com/unicef/publicgoods-scripts).

**Comment by lacabra** [comment]
An initial implementation by Edil can be found [here](https://digital-public-goods-map-rolikasi.vercel.app/) and a design [here](https://www.figma.com/file/yi1iu3lUapluexM83H6z3h/digital-public-goods-map?node-id=0%3A1), and repo [here](https://github.com/Rolikasi/digital-public-goods-map). Map is able to pull data from JSONs in publicgoods-candidates and Google Spreadsheets. It uses react-mapbox-gl to render the map.

Here is Edil's proposed timeline for this project:

Week 1:
- get to know the UNICEF Innovation team 👋🏽
- discuss and improve the [design](https://www.figma.com/file/yi1iu3lUapluexM83H6z3h/digital-public-goods-map?node-id=0%3A1) of the map I have developed. Exported [jpg](https://drive.google.com/file/d/1WuWEdKEhhEbZkAiaWqbfuCsjqGxsOnql/view?usp=sharing) version
- invite team to collaborate in [Figma design](https://www.figma.com/file/yi1iu3lUapluexM83H6z3h/digital-public-goods-map?node-id=0%3A1)
- show the team my [prototype](https://digital-public-goods-map-rolikasi.vercel.app/) and [repo](https://github.com/Rolikasi/digital-public-goods-map) with current implementation
- discuss new ideas, workflows and how we will reveal the story through digital goods map.
- align colors, fonts and styles with [UNICEF brand guidelines](https://github.com/Rolikasi/digital-public-goods-map)

Week 2:
- improve my standalone [prototype](https://digital-public-goods-map-rolikasi.vercel.app/) of the map 👨🏽‍💻
- add links to repo and data,
- improve Info component,
- improve select box (need to change string of the parent search box when user clicks on the good),
- add styling that follows [UNICEF brand guidelines](https://digital-public-goods-map-rolikasi.vercel.app/)
- work on README and CONTRIBUTING files in [repo](https://github.com/Rolikasi/digital-public-goods-map)
- nominate digital public goods

Week 3:
- add storytelling components to the map with react-scrollama (see visual reference https://pudding.cool/2021/04/music-bubble/ or https://pudding.cool/2018/12/3d-cities-story/)
- add ESlint, husky, prettier
- create function that will pull information with text from googlesheets or googledoc to storytelling components
- add reviews for digital public goods 👀

Week 4:
- add an additional layer of visualization with 3d polygons on a pitched map to graphically show how many goods were developed and implemented in each country. (visual reference https://pudding.cool/2018/12/3d-cities-story/ and the last component at the bottom in my design of the map https://drive.google.com/file/d/1WuWEdKEhhEbZkAiaWqbfuCsjqGxsOnql/view?usp=sharing)
- add responsive design to the map
- add reviews 👀

Week 5:
- improve initial rendering of the map. Now it re-renders each time when json is loaded. One of the workarounds is to add loading component that will be shown until all files are loaded.
- add nominees

Weeks 6-7:
- finish a story (or a guide) of the map
- seek and fix bugs
- deploy map to the https://digitalpublicgoods.net/map . I guess I'll make script in publicgoods-scripts repo that will create a new path in publicgoods-website repo.
- add reviews 👀

Weeks 8-13:
- add new features if have any
- seek and fix bugs after deployment to the main site
- improve layouts and fix bugs in other sections of the digitalpublicgoods.net site:
- fix issues I added here
- make site mobile friendly
- add JS linter to all repos
- add nominees
- add reviews 👀

Technologies for the digital goods map project: JavaScript, React, react mapbox-gl, JSON, react-scrollama, g-sheets-api, github-api, eslint, husky, prettier, figma

**Comment by edil-it-them** [comment]
Based on discussion with comms and pathfinders teams we agreed to develop 2 separate maps for DPGs and Pathfinders with 2 different stories. They will suit use cases like advocacy presentations for governments and organizations, investors, private sector, potential DPGs, tell success stories and will not overwhelmingly overlap with each other.
[Current design](https://www.figma.com/file/yi1iu3lUapluexM83H6z3h/digital-public-goods-map?node-id=1%3A359) and [repo](https://github.com/Rolikasi/digital-public-goods-map) for the map visualization.

Proposed steps:
- [x] develop a flexible reusable map component which will be suitable for Pathfinders and DPGs sections and also could be a standalone visualization with all layers of data.
  - [x] add responsiveness  
  - [x] update the design according to the [DPGa guidelines](https://drive.google.com/file/d/10Vv40tqHDsIKClKGR4no7r0WinG5NX3p/view)
  - [x] add a storytelling component
  - [x] add a ability to mix storytelling with images and videos
  - [x] develop integration with google doc. We need an ability to parse the text from doc into structured jsons so non-technical staff can edit text for storytelling components. (Or use google spreadsheets)
  - [x] graphically show how many DGPs are implemented and developed in each country
  - [x] develop an info component with information about selected DPG
  - [x] add linter
  - [x] show popups with information on countries
  - [x] show countries in which a good was developed
  - [x] show countries where the good has been implemented
  - [x] show countries participating in the Pathfinder activities of the Digital Public Goods Alliance (think of early adopters)
  - [x] show countries with implementations of goods part of the DPGA communities of practice: Digital Health, Climate Adaptation, Financial Inclusion
  - [x] pull data from set of JSONs
  - [x] pull data from google spreadsheets


- [x] integrate standalone map visualization

- [ ] integrate map for DPG story (in [registry section](https://digitalpublicgoods.net/registry/)?)
  - [ ] create story and text 
  
- [ ] integrate map in [Pathfinders Countries section](https://digitalpublicgoods.net/what-we-do/) to improve heavy text mixing it with images and videos (technical idea like in this [Washinghtonpost article](https://www.washingtonpost.com/graphics/2018/local/dc-riots-1968/))
  - [ ] create a story and text
  
- [ ] create documentation on how to update stories

**Comment by nathanfletcher** [comment]
A couple of screenshots from the latest update are below. 3D bar graph visualizations.
![New layer of visualization.PNG](https://images.zenhubusercontent.com/60c9f3c5e24126113185cd7b/db6cc12a-c380-4075-a42e-2e04e04704bb)
![New layer of visualization 1 on.PNG](https://images.zenhubusercontent.com/60c9f3c5e24126113185cd7b/9f57285e-2d5e-4fa5-b6cc-6b89b872a682)

**Comment by edil-it-them** [comment]
MVP is ready. 
But before moving forward I want to add an ability to select country from a dropdown list and display summary information with charts about DPGs activity in each country.  
**Proposed feature**
- [x] add list of countries in searchBox
- [x] clicking on countries from list zooms to country
- [x] clicking on countries displays information about country
  - [x] How many goods are deployed and developed
  - [x] Pathfinder data
  - [x] How many deployed DPGs are related to each SDG in country
  - [x] which and how many types of DPGs are deployed in country
[Related issue](https://github.com/Rolikasi/digital-public-goods-map/issues/53), [current implementation](https://digital-public-goods-map.vercel.app/)
