### ISSUE TITLE
Create Roadmap for Kindly Project

### ISSUE THREAD

**Issue by amreenp7** [unicef/publicgoods-roadmap#67]
- [x] Create a detailed roadmap based on discussions with Victor and Nathan F
- [x] Create High-level version that can be included in the GH Repo
- [x] Create tasks from the roadmap line items

Latest working version can be found here: https://docs.google.com/spreadsheets/d/1NaLrLPaiLW5TZSvVpgofXZmYaFs9UtmwFJd1NcrTcdY/edit#gid=1936932112

**Comment by amreenp7** [comment]
Created tickets for early roadmap items:
- Vision document
- Blog
- Documentation (ongoing)
- Partner engagement strategy 
- Front-end for gathering data

These can be found in ZH by just filtering for the "Kindly" epic.
